name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run my GitHub action
        uses: ./
        with:
          github_pat: ${{ secrets.GITHUB_TOKEN }}
